### ISSUE TITLE
Navbar overlays action buttons

### ISSUE THREAD

**Issue by franco27** [LinkSheet/LinkSheet#357]
Hello

I just tried the latest Nightly version.
I am using Android 10.

After selecting your app in the Android Share window.
The window of your app opens and there is a list of apps.
I can select an app but I cannot click on the button. See the screenshot.
Because the Android navigation bar is in the foreground covering your buttons.

![IMG_20240317_191231](https://github.com/1fexd/LinkSheetNightly/assets/31793920/46c6bca7-b62e-4c78-86b7-38129b78dacb)

**Comment by 1fexd** [comment]
Could you please export the log (with preferences) and maybe (if possible) a short screen recoding?

**Comment by 1fexd** [comment]
Should be fixed now, please try [1710957358](https://github.com/1fexd/LinkSheetNightly/releases/tag/1710957358)

**Comment by franco27** [comment]
It is still not resolved.

On the scrolling window with the applications, there are still buttons located below the phone's navigation bar.

I don't have an error message, but I can't click on the buttons at the bottom of the screen.

**Comment by 1fexd** [comment]
Screen recording?

**Comment by 1fexd** [comment]
Could you please test if this issue still occurs on the latest nightly build?

**Comment by franco27** [comment]
When the window of your application appears and I scroll upwards, your buttons always end up below or behind the Android navigation buttons. 

This prevents me from clicking on them.
If I scroll down and then back up, I get the same result and it's impossible to click on any of the buttons. 
These buttons appear on screen but are always behind the bottom Android navigation bar.
I have downloaded and installed version 1711745809.

This is still not resolved.

![IMG_20240329_225824.jpg](https://github.com/1fexd/LinkSheet/assets/31793920/0167dd76-bd63-4cb2-becc-fa603fad2c80)

**Comment by franco27** [comment]
![IMG_20240329_225625.jpg](https://github.com/1fexd/LinkSheet/assets/31793920/c25b4c85-6baf-47ef-9dd6-4d225c1b3d45)

Here is my smartphone system configuration:
Xiaomi Redmi 8
Android Version 10 Android 10
MIUI V12.5.2.0.QCNEUXM

Architecture 64-bit

Instruction sets
arm64-v8a armeabi-v7a armeabi Qualcomm® Snapdragon™ 439

CPU 4 x Cortex-A53
Cores 8
RAM size 4 GB

**Comment by 1fexd** [comment]
Could you please check if [1711840011](https://github.com/1fexd/LinkSheetNightly/releases/tag/1711840011) fixes the issue?

**Comment by franco27** [comment]
Now I confirm to you that it is resolved.
I can now click on one of the buttons.
Thank you.

![IMG_20240331_210710.jpg](https://github.com/LinkSheet/LinkSheet/assets/31793920/bf23768e-e7de-47af-8a42-b888cc5d25e5)

![IMG_20240331_211021.jpg](https://github.com/LinkSheet/LinkSheet/assets/31793920/a368cce6-9ccb-44f3-9f9c-f231576dd145)
