### ISSUE TITLE
Issue when using new verified link page in experiments and issue with enabling clearurl

### ISSUE THREAD

**Issue by Sahibishere** [LinkSheet/LinkSheet#632]
### Bug description

When I try to change link handler for tor browser, I get a error when I wrote in the crash log. When enabling clear urls, urls like for store.epicgames.com don't work properly, such as this link https://store.epicgames.com/purchase?offers=1-e52b4d8cbcfd45ad95eff800ccc59d93-54003c89a604467abe315658a4a853b3&offers=1-99d8ac4b0cd94611b52bae792d84b0e4-5e416c7c1444483e828899b0c30ce2cd, this is the link I get with clearurls disabled and it shows both the 2 items/games correctly, but when I use clearurls I get this link: https://store.epicgames.com/purchase?offers=1-99d8ac4b0cd94611b52bae792d84b0e4-5e416c7c1444483e828899b0c30ce2cd, which only shows 1 item/game. 

### Version

nightly-2025082901-nightly

### Device

Samsung Galaxy S23 Ultra

### Android version

Android 15 (Stock)

### Application log or crash log

:{
  "build_info": {
    "built_at": "2025-08-29 22:56:18",
    "flavor": "Foss-nightly",
    "version_code": 2025082901,
    "version_name": "nightly-2025082901-nightly",
    "workflow_id": "17314222246"
  },
  "device_info": {
    "android_version": "15",
    "manufacturer": "samsung",
    "model": "SM-S918U1"
  },
  "locale": "en-US",
  "fingerprint": "samsung/dm3quew/dm3q:15/AP3A.240905.015.A2/S918U1UES6DYG1:user/release-keys",
  "active_experiments": [
    "experiment_impr_btm_sheet_expand_fully",
    "experiment_impr_btm_sheet_url_double_tap",
    "experiment_intercept_accidental_taps",
    "experiment_hide_referrer_from_sheet",
    "experiment_expressive_loading_sheet",
    "experiment_link_engine"
  ],
  "preferences": [
    {
      "name": "hide_after_copying",
      "value": "false"
    },
    {
      "name": "usage_stats_sorting",
      "value": "true"
    },
    {
      "name": "browser_mode",
      "value": "Whitelisted"
    },
    {
      "name": "selected_browser",
      "value": "cdab3149f5949870a958fe43524c7e6e3aade238daddd5e32006c83db22b9102"
    },
    {
      "name": "in_app_browser_mode",
      "value": "AlwaysAsk"
    },
    {
      "name": "selected_in_app_browser",
      "value": "<null>"
    },
    {
      "name": "unified_preferred_browser",
      "value": "true"
    },
    {
      "name": "in_app_browser_setting",
      "value": "UseAppSettings"
    },
    {
      "name": "url_copied_toast",
      "value": "true"
    },
    {
      "name": "download_started_toast",
      "value": "true"
    },
    {
      "name": "opening_with_app_toast",
      "value": "true"
    },
    {
      "name": "resolve_via_toast",
      "value": "true"
    },
    {
      "name": "resolve_via_failed_toast",
      "value": "true"
    },
    {
      "name": "always_show_package_name",
      "value": "false"
    },
    {
      "name": "grid_layout",
      "value": "true"
    },
    {
      "name": "use_clear_urls",
      "value": "false"
    },
    {
      "name": "fast_forward_rules",
      "value": "true"
    },
    {
      "name": "follow_redirects",
      "value": "false"
    },
    {
      "name": "follow_redirects_local_cache",
      "value": "true"
    },
    {
      "name": "follow_redirects_external_service",
      "value": "false"
    },
    {
      "name": "follow_only_known_trackers",
      "value": "false"
    },
    {
      "name": "follow_redirects_allow_darknets",
      "value": "false"
    },
    {
      "name": "follow_redirects_allow_local_network",
      "value": "false"
    },
    {
      "name": "follow_redirects_skip_browser",
      "value": "true"
    },
    {
      "name": "dont_show_filtered_item",
      "value": "true"
    },
    {
      "name": "enable_downloader",
      "value": "true"
    },
    {
      "name": "downloaderCheckUrlMimeType",
      "value": "false"
    },
    {
      "name": "enable_ignore_lib_redirect_button",
      "value": "false"
    },
    {
      "name": "enable_lib_redirect",
      "value": "false"
    },
    {
      "name": "follow_redirects_timeout",
      "value": "15"
    },
    {
      "name": "enable_amp2html",
      "value": "false"
    },
    {
      "name": "amp2html_local_cache",
      "value": "true"
    },
    {
      "name": "amp2html_external_service",
      "value": "false"
    },
    {
      "name": "amp2html_allow_darknets",
      "value": "false"
    },
    {
      "name": "amp2html_allow_local_network",
      "value": "false"
    },
    {
      "name": "amp2html_skip_browser",
      "value": "true"
    },
    {
      "name": "enable_request_private_browsing_button",
      "value": "true"
    },
    {
      "name": "show_as_referrer",
      "value": "false"
    },
    {
      "name": "dev_mode_enabled",
      "value": "false"
    },
    {
      "name": "first_run",
      "value": "true"
    },
    {
      "name": "show_discord_banner",
      "value": "true"
    },
    {
      "name": "donate_card_dismissed",
      "value": "false"
    },
    {
      "name": "resolve_embeds",
      "value": "true"
    },
    {
      "name": "hide_bottom_sheet_choice_buttons",
      "value": "true"
    },
    {
      "name": "telemetry_dialog",
      "value": "true"
    },
    {
      "name": "last_version",
      "value": "2025082901"
    },
    {
      "name": "theme_v2",
      "value": "System"
    },
    {
      "name": "theme_material_you",
      "value": "true"
    },
    {
      "name": "theme_amoled_enabled",
      "value": "true"
    },
    {
      "name": "tap_config_single",
      "value": "OpenApp"
    },
    {
      "name": "tap_config_double",
      "value": "OpenSettings"
    },
    {
      "name": "tap_config_long",
      "value": "SelectItem"
    },
    {
      "name": "expand_on_app_select",
      "value": "true"
    },
    {
      "name": "bottom_sheet_native_label",
      "value": "true"
    },
    {
      "name": "installation_id"
    },
    {
      "name": "bottom_sheet_profile_switcher",
      "value": "false"
    },
    {
      "name": "last_versions_v0",
      "value": "[{\"v\":2025071402,\"f\":\"Foss-nightly\"},{\"v\":2025072502,\"f\":\"Foss-nightly\"},{\"v\":2025080101,\"f\":\"Foss-nightly\"},{\"v\":2025080301,\"f\":\"Foss-nightly\"},{\"v\":2025082303,\"f\":\"Foss-nightly\"},{\"v\":2025082901,\"f\":\"Foss-nightly\"}]"
    },
    {
      "name": "home_clipboard_card",
      "value": "true"
    },
    {
      "name": "remote_config",
      "value": "true"
    },
    {
      "name": "preview_url",
      "value": "true"
    },
    {
      "name": "url_bar_preview",
      "value": "false"
    },
    {
      "name": "url_bar_preview_skip_browser",
      "value": "false"
    },
    {
      "name": "theme",
      "value": "0"
    }
  ],
  "log": [
    {
      "type": "Crash",
      "time": "2025-08-30T14:40:34.218",
      "message": "java.lang.IllegalArgumentException: Group size must be greater than 0\n\tat T5.j.k(SourceFile:16)\n\tat A.W.i(SourceFile:26)\n\tat U6.a.D(SourceFile:120)\n\tat b6.e.D(SourceFile:133)\n\tat K.i.<init>(SourceFile:11)\n\tat K.o.b(SourceFile:40)\n\tat F0.g$a.c(SourceFile:51)\n\tat v0.J.z(SourceFile:286)\n\tat v0.J.getValue(SourceFile:34)\n\tat K.p.b(SourceFile:64)\n\tat F0.g$a.c(SourceFile:51)\n\tat v0.J.z(SourceFile:286)\n\tat v0.J.s(SourceFile:21)\n\tat F0.D$a.c(SourceFile:46)\n\tat F0.B.D(SourceFile:86)\n\tat v0.J.getValue(SourceFile:16)\n\tat K.q.get(SourceFile:19)\n\tat J9.v.b(SourceFile:1)\n\tat M.F.b(SourceFile:36)\n\tat M.L.<init>(SourceFile:10)\n\tat A.G.invoke(SourceFile:176)\n\tat androidx.compose.ui.layout.m.e(SourceFile:68)\n\tat h1.w.j(SourceFile:49)\n\tat O0.t0.e(SourceFile:1)\n\tat h1.D.j(SourceFile:179)\n\tat M.l.e(SourceFile:1)\n\tat h1.D.j(SourceFile:179)\n\tat I.G.e(SourceFile:105)\n\tat h1.D.j(SourceFile:179)\n\tat I.y0.e(SourceFile:104)\n\tat h1.D.j(SourceFile:179)\n\tat h1.U$b.b(SourceFile:11)\n\tat F0.g$a.c(SourceFile:51)\n\tat F0.D$a.a(SourceFile:61)\n\tat F0.D.d(SourceFile:128)\n\tat h1.C0.a(SourceFile:3)\n\tat h1.U.x0(SourceFile:38)\n\tat h1.U.H0(SourceFile:112)\n\tat h1.U.j(SourceFile:99)\n\tat I.m.e(SourceFile:83)\n\tat h1.w.j(SourceFile:49)\n\tat h1.U$b.b(SourceFile:11)\n\tat F0.g$a.c(SourceFile:51)\n\tat F0.D$a.a(SourceFile:61)\n\tat F0.D.d(SourceFile:128)\n\tat h1.C0.a(SourceFile:3)\n\tat h1.U.x0(SourceFile:38)\n\tat h1.U.H0(SourceFile:112)\n\tat h1.U.j(SourceFile:99)\n\tat p0.S3.invoke(SourceFile:402)\n\tat androidx.compose.ui.layout.m.e(SourceFile:68)\n\tat h1.w.j(SourceFile:49)\n\tat h1.U$b.b(SourceFile:11)\n\tat F0.g$a.c(SourceFile:51)\n\tat F0.D$a.a(SourceFile:61)\n\tat F0.D.d(SourceFile:128)\n\tat h1.C0.a(SourceFile:3)\n\tat h1.U.x0(SourceFile:38)\n\tat h1.U.H0(SourceFile:112)\n\tat h1.U.j(SourceFile:99)\n\tat I.m.e(SourceFile:83)\n\tat h1.w.j(SourceFile:49)\n\tat O0.t0.e(SourceFile:1)\n\tat h1.D.j(SourceFile:179)\n\tat I.G.e(SourceFile:105)\n\tat h1.D.j(SourceFile:179)\n\tat h1.U$b.b(SourceFile:11)\n\tat F0.g$a.c(SourceFile:51)\n\tat F0.D$a.a(SourceFile:61)\n\tat F0.D.d(SourceFile:128)\n\tat h1.C0.a(SourceFile:3)\n\tat h1.U.x0(SourceFile:38)\n\tat h1.U.H0(SourceFile:112)\n\tat h1.U.j(SourceFile:99)\n\tat x.m.e(SourceFile:25)\n\tat h1.w.j(SourceFile:49)\n\tat x.Z.e(SourceFile:107)\n\tat h1.D.j(SourceFile:179)\n\tat O0.L.e(SourceFile:1)\n\tat h1.D.j(SourceFile:179)\n\tat x.c.C(SourceFile:9)\n\tat f1.z.e(SourceFile:8)\n\tat h1.D.j(SourceFile:179)\n\tat h1.U$b.b(SourceFile:11)\n\tat F0.g$a.c(SourceFile:51)\n\tat F0.D$a.a(SourceFile:61)\n\tat F0.D.d(SourceFile:128)\n\tat h1.C0.a(SourceFile:3)\n\tat h1.U.x0(SourceFile:38)\n\tat h1.U.H0(SourceFile:112)\n\tat h1.U.j(SourceFile:99)\n\tat androidx.compose.animation.c.e(SourceFile:68)\n\tat h1.w.j(SourceFile:49)\n\tat androidx.compose.animation.AnimatedContentTransitionScopeImpl$b.e(SourceFile:1)\n\tat h1.D.j(SourceFile:179)\n\tat h1.U$b.b(SourceFile:11)\n\tat F0.g$a.c(SourceFile:109)\n\tat F0.D$a.a(SourceFile:61)\n\tat F0.D.d(SourceFile:128)\n\tat h1.C0.a(SourceFile:3)\n\tat h1.U.x0(SourceFile:38)\n\tat h1.U.H0(SourceFile:112)\n\tat h1.F.X(SourceFile:18)\n\tat h1.F.Y(SourceFile:18)\n\tat h1.T.c(SourceFile:8)\n\tat h1.T.m(SourceFile:124)\n\tat h1.T.g(SourceFile:105)\n\tat h1.T.g(SourceFile:119)\n\tat h1.T.f(SourceFile:28)\n\tat androidx.compose.ui.platform.AndroidComposeView.r(SourceFile:3)\n\tat h1.U.H0(SourceFile:63)\n\tat h1.F.X(SourceFile:18)\n\tat h1.T.c(SourceFile:3)\n\tat h1.T.o(SourceFile:23)\n\tat h1.T.l(SourceFile:89)\n\tat androidx.compose.ui.platform.AndroidComposeView.onMeasure(SourceFile:83)\n\tat android.view.View.measure(View.java:29591)\n\tat i1.a.g(SourceFile:64)\n\tat i1.a.onMeasure(SourceFile:4)\n\tat android.view.View.measure(View.java:29591)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7383)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:207)\n\tat androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)\n\tat android.view.View.measure(View.java:29591)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7383)\n\tat android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)\n\tat android.widget.LinearLayout.measureVertical(LinearLayout.java:878)\n\tat android.widget.LinearLayout.onMeasure(LinearLayout.java:721)\n\tat android.view.View.measure(View.java:29591)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7383)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:207)\n\tat android.view.View.measure(View.java:29591)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7383)\n\tat android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)\n\tat android.widget.LinearLayout.measureVertical(LinearLayout.java:878)\n\tat android.widget.LinearLayout.onMeasure(LinearLayout.java:721)\n\tat android.view.View.measure(View.java:29591)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7383)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:207)\n\tat com.android.internal.policy.DecorView.onMeasure(DecorView.java:1037)\n\tat android.view.View.measure(View.java:29591)\n\tat android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5824)\n\tat android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:4043)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4402)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3708)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:12542)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:1751)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:1760)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:1216)\n\tat android.view.Choreographer.doFrame(Choreographer.java:1142)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1707)\n\tat android.os.Handler.handleCallback(Handler.java:959)\n\tat android.os.Handler.dispatchMessage(Handler.java:100)\n\tat android.os.Looper.loopOnce(Looper.java:257)\n\tat android.os.Looper.loop(Looper.java:342)\n\tat android.app.ActivityThread.main(ActivityThread.java:9634)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:619)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)\n"
    },
    {
      "type": "I",
      "time": "2025-08-30T14:40:34.334",
      "prefix": "AppStateService",
      "redactedMessage": "Updates required: 0"
    }
  ]
}

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Should be fixed in the latest nightly build.

**Comment by Sahibishere** [comment]
> Should be fixed in the latest nightly build.

Hi the clearurls part works fine now, but the new vlh(verified link handler page) still crashes whenever I click on tor browser with the exact same error.
